// Code generated by protoc-gen-go.
// source: hn.proto
// DO NOT EDIT!

/*
Package gohn is a generated protocol buffer package.

It is generated from these files:
	hn.proto

It has these top-level messages:
	Item
*/
package gohn

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Item struct {
	By               *string `protobuf:"bytes,1,opt,name=by" json:"by,omitempty"`
	Descendants      *int64  `protobuf:"varint,2,opt,name=descendants" json:"descendants,omitempty"`
	Id               *int64  `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Kids             []int64 `protobuf:"varint,4,rep,name=kids" json:"kids,omitempty"`
	Parent           *int64  `protobuf:"varint,5,opt,name=parent" json:"parent,omitempty"`
	Parts            []int64 `protobuf:"varint,6,rep,name=parts" json:"parts,omitempty"`
	Score            *int64  `protobuf:"varint,7,opt,name=score" json:"score,omitempty"`
	Text             *string `protobuf:"bytes,8,opt,name=text" json:"text,omitempty"`
	Time             *int64  `protobuf:"varint,9,opt,name=time" json:"time,omitempty"`
	Title            *string `protobuf:"bytes,10,opt,name=title" json:"title,omitempty"`
	Type             *string `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Url              *string `protobuf:"bytes,12,opt,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}

func (m *Item) GetBy() string {
	if m != nil && m.By != nil {
		return *m.By
	}
	return ""
}

func (m *Item) GetDescendants() int64 {
	if m != nil && m.Descendants != nil {
		return *m.Descendants
	}
	return 0
}

func (m *Item) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Item) GetKids() []int64 {
	if m != nil {
		return m.Kids
	}
	return nil
}

func (m *Item) GetParent() int64 {
	if m != nil && m.Parent != nil {
		return *m.Parent
	}
	return 0
}

func (m *Item) GetParts() []int64 {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *Item) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Item) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Item) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Item) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func init() {
}
